"""Tests for task state tracking."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from pathlib import Path

from intake.utils.task_state import (
    VALID_STATUSES,
    TaskStateError,
    TaskStateManager,
    TaskStatus,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

SAMPLE_TASKS_MD = """\
# Implementation Tasks

> Auto-generated by intake. Do not edit manually.

| ID | Title | Status | Est. Minutes | Dependencies |
|----|-------|--------|-------------|--------------|
| 1 | Set up project structure | pending | 15 | none |
| 2 | Implement authentication | pending | 30 | 1 |
| 3 | Write tests | pending | 20 | 1, 2 |

---

## Task 1: Set up project structure

Create the initial project directory layout.

**Status:** pending
**Estimated time:** 15 minutes

**Files:**
- `src/app.py`

## Task 2: Implement authentication

Add OAuth2 authentication flow.

**Status:** pending
**Estimated time:** 30 minutes
**Depends on:** 1

**Files:**
- `src/auth.py`
- `src/middleware.py`

## Task 3: Write tests

Write unit and integration tests.

**Status:** pending
**Estimated time:** 20 minutes
**Depends on:** 1, 2

**Files:**
- `tests/test_auth.py`
"""


def _create_spec_dir(tmp_path: Path, content: str = SAMPLE_TASKS_MD) -> Path:
    """Create a spec directory with a tasks.md file."""
    spec_dir = tmp_path / "test-spec"
    spec_dir.mkdir()
    (spec_dir / "tasks.md").write_text(content, encoding="utf-8")
    return spec_dir


# ---------------------------------------------------------------------------
# Tests — TaskStatus dataclass
# ---------------------------------------------------------------------------


class TestTaskStatus:
    def test_creation(self) -> None:
        status = TaskStatus(id=1, title="Test", status="pending")
        assert status.id == 1
        assert status.title == "Test"
        assert status.status == "pending"
        assert status.description == ""

    def test_with_description(self) -> None:
        status = TaskStatus(id=1, title="Test", status="done", description="All done")
        assert status.description == "All done"


# ---------------------------------------------------------------------------
# Tests — TaskStateError
# ---------------------------------------------------------------------------


class TestTaskStateError:
    def test_message_without_suggestion(self) -> None:
        err = TaskStateError(reason="not found")
        assert "not found" in str(err)

    def test_message_with_suggestion(self) -> None:
        err = TaskStateError(reason="invalid", suggestion="try again")
        assert "invalid" in str(err)
        assert "try again" in str(err)


# ---------------------------------------------------------------------------
# Tests — TaskStateManager
# ---------------------------------------------------------------------------


class TestTaskStateManager:
    def test_list_tasks(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))
        tasks = manager.list_tasks()

        assert len(tasks) == 3
        assert tasks[0].id == 1
        assert tasks[0].title == "Set up project structure"
        assert tasks[0].status == "pending"

    def test_list_tasks_with_status_filter(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        # All pending initially
        tasks = manager.list_tasks(status_filter=["pending"])
        assert len(tasks) == 3

        # No done tasks
        tasks = manager.list_tasks(status_filter=["done"])
        assert len(tasks) == 0

    def test_list_tasks_file_not_found(self, tmp_path: Path) -> None:
        spec_dir = tmp_path / "empty-spec"
        spec_dir.mkdir()
        manager = TaskStateManager(str(spec_dir))

        with pytest.raises(TaskStateError, match="not found"):
            manager.list_tasks()

    def test_get_task(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        task = manager.get_task(2)
        assert task.id == 2
        assert task.title == "Implement authentication"
        assert task.status == "pending"

    def test_get_task_not_found(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        with pytest.raises(TaskStateError, match="Task 99 not found"):
            manager.get_task(99)

    def test_update_task_status(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        updated = manager.update_task(1, "in_progress")
        assert updated.id == 1
        assert updated.status == "in_progress"

        # Verify it was persisted
        task = manager.get_task(1)
        assert task.status == "in_progress"

    def test_update_task_with_note(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        manager.update_task(2, "done", note="All tests pass")

        # Read the file content to verify the note was written
        content = (spec_dir / "tasks.md").read_text(encoding="utf-8")
        assert "done" in content
        assert "All tests pass" in content

    def test_update_task_invalid_status(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        with pytest.raises(TaskStateError, match="Invalid status"):
            manager.update_task(1, "invalid_status")

    def test_update_task_not_found(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        with pytest.raises(TaskStateError, match="Task 99 not found"):
            manager.update_task(99, "done")

    def test_update_preserves_other_tasks(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        manager.update_task(1, "done")

        # Task 2 and 3 should still be pending
        task2 = manager.get_task(2)
        task3 = manager.get_task(3)
        assert task2.status == "pending"
        assert task3.status == "pending"

    def test_multiple_updates(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        manager.update_task(1, "in_progress")
        manager.update_task(1, "done")
        manager.update_task(2, "in_progress")

        tasks = manager.list_tasks()
        statuses = {t.id: t.status for t in tasks}
        assert statuses[1] == "done"
        assert statuses[2] == "in_progress"
        assert statuses[3] == "pending"

    def test_valid_statuses_constant(self) -> None:
        assert "pending" in VALID_STATUSES
        assert "in_progress" in VALID_STATUSES
        assert "done" in VALID_STATUSES
        assert "blocked" in VALID_STATUSES

    def test_filter_after_update(self, tmp_path: Path) -> None:
        spec_dir = _create_spec_dir(tmp_path)
        manager = TaskStateManager(str(spec_dir))

        manager.update_task(1, "done")
        manager.update_task(2, "in_progress")

        done_tasks = manager.list_tasks(status_filter=["done"])
        assert len(done_tasks) == 1
        assert done_tasks[0].id == 1

        active_tasks = manager.list_tasks(status_filter=["in_progress"])
        assert len(active_tasks) == 1
        assert active_tasks[0].id == 2
