"""Architect exporter — generates pipeline.yaml for the architect tool.

Produces:
- pipeline.yaml: Workflow with one step per task + final verification
- spec/: Copy of the 6 spec files for reference
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

import structlog
import yaml

logger = structlog.get_logger()


class ArchitectExporter:
    """Generate output ready for architect.

    Produces a pipeline.yaml with one step per task from tasks.md,
    checks from acceptance.yaml, and copies all spec files.
    """

    def __init__(self, include_guardrails: bool = True) -> None:
        self.include_guardrails = include_guardrails

    def export(self, spec_dir: str, output_dir: str) -> list[str]:
        """Export the spec as an architect pipeline.

        Args:
            spec_dir: Path to the spec directory.
            output_dir: Path to write exported files.

        Returns:
            List of generated file paths.
        """
        spec_path = Path(spec_dir)
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        generated: list[str] = []

        tasks = self._load_tasks(spec_path / "tasks.md")
        checks = self._load_acceptance(spec_path / "acceptance.yaml")
        context = self._read_file(spec_path / "context.md")

        pipeline = self._build_pipeline(tasks, checks, spec_path.name, context)
        pipeline_path = out_path / "pipeline.yaml"
        pipeline_path.write_text(
            yaml.dump(pipeline, default_flow_style=False, allow_unicode=True),
            encoding="utf-8",
        )
        generated.append(str(pipeline_path))

        # Copy spec files for reference
        spec_out = out_path / "spec"
        spec_out.mkdir(exist_ok=True)
        for f in spec_path.iterdir():
            if f.is_file():
                dest = spec_out / f.name
                shutil.copy2(f, dest)
                generated.append(str(dest))

        logger.info(
            "architect_export_complete",
            pipeline=str(pipeline_path),
            files=len(generated),
        )

        return generated

    def _build_pipeline(
        self,
        tasks: list[dict[str, str]],
        checks: list[dict[str, object]],
        spec_name: str,
        context: str,
    ) -> dict[str, object]:
        """Build the architect pipeline structure.

        Args:
            tasks: Parsed tasks from tasks.md.
            checks: Parsed checks from acceptance.yaml.
            spec_name: Name of the spec.
            context: Project context text.

        Returns:
            Pipeline dict ready for YAML serialization.
        """
        steps: list[dict[str, object]] = []

        for task in tasks:
            step: dict[str, object] = {
                "name": f"task-{task['id']}",
                "agent": "build",
                "prompt": (
                    f"Implement task {task['id']}: {task['title']}\n\n"
                    f"{task.get('description', '')}\n\n"
                    f"Project context:\n{context[:2000]}"
                ),
                "checkpoint": True,
            }
            if task.get("checks"):
                step["checks"] = task["checks"]
            steps.append(step)

        # Final verification step with all required command checks
        required_commands = [
            str(c["command"])
            for c in checks
            if c.get("type") == "command" and c.get("required", True) and c.get("command")
        ]
        if required_commands:
            steps.append(
                {
                    "name": "final-verification",
                    "agent": "review",
                    "prompt": "Verify that the entire implementation meets the spec requirements.",
                    "checks": required_commands,
                }
            )

        return {
            "name": spec_name,
            "description": f"Pipeline generated by intake from spec '{spec_name}'",
            "steps": steps,
        }

    def _load_tasks(self, path: Path) -> list[dict[str, str]]:
        """Parse tasks.md and extract structured tasks.

        Extracts task ID, title, and description from markdown headings
        matching the pattern: ### Task N: Title or ### N: Title

        Args:
            path: Path to tasks.md.

        Returns:
            List of task dicts with id, title, description keys.
        """
        if not path.exists():
            return []

        content = path.read_text(errors="ignore")
        tasks: list[dict[str, str]] = []
        current_task: dict[str, str] | None = None
        description_lines: list[str] = []

        for line in content.splitlines():
            # Match task headings: ### Task 1: Title or ### 1: Title or ### 1. Title
            match = re.match(
                r"^###?\s+(?:Task\s+)?(\d+)[:.]\s*(.*)",
                line,
                re.IGNORECASE,
            )
            if match:
                # Save previous task
                if current_task is not None:
                    current_task["description"] = "\n".join(description_lines).strip()
                    tasks.append(current_task)

                current_task = {
                    "id": match.group(1),
                    "title": match.group(2).strip(),
                    "checks": "",
                }
                description_lines = []
            elif current_task is not None:
                # Skip sub-headings that start new non-task sections
                if re.match(r"^#{1,2}\s+", line):
                    current_task["description"] = "\n".join(description_lines).strip()
                    tasks.append(current_task)
                    current_task = None
                    description_lines = []
                else:
                    description_lines.append(line)

        # Save last task
        if current_task is not None:
            current_task["description"] = "\n".join(description_lines).strip()
            tasks.append(current_task)

        return tasks

    def _load_acceptance(self, path: Path) -> list[dict[str, object]]:
        """Load acceptance.yaml checks.

        Args:
            path: Path to acceptance.yaml.

        Returns:
            List of check definitions.
        """
        if not path.exists():
            return []
        with open(path) as f:
            data = yaml.safe_load(f)
        if not isinstance(data, dict):
            return []
        checks = data.get("checks", [])
        return checks if isinstance(checks, list) else []

    def _read_file(self, path: Path) -> str:
        """Read a text file, returning empty string if missing.

        Args:
            path: Path to the file.

        Returns:
            File content or empty string.
        """
        if not path.exists():
            return ""
        return path.read_text(errors="ignore")
