"""Generic exporter — universal Markdown summary + verify.sh.

Produces:
- SPEC.md: Consolidated Markdown with all spec sections
- verify.sh: Shell script that runs acceptance command checks
- spec/: Copy of the 6 spec files for reference
"""

from __future__ import annotations

import shutil
import stat
from pathlib import Path

import structlog
import yaml

logger = structlog.get_logger()

VERIFY_HEADER = """#!/usr/bin/env bash
# Auto-generated by intake — run acceptance checks for {spec_name}
# Usage: bash verify.sh [project_dir]

set -euo pipefail

PROJECT_DIR="${{1:-.}}"
PASSED=0
FAILED=0
TOTAL=0

check() {{
    local name="$1"
    local cmd="$2"
    TOTAL=$((TOTAL + 1))
    echo -n "  [$TOTAL] $name ... "
    if (cd "$PROJECT_DIR" && eval "$cmd") > /dev/null 2>&1; then
        echo "PASS"
        PASSED=$((PASSED + 1))
    else
        echo "FAIL"
        FAILED=$((FAILED + 1))
    fi
}}

echo "=== Verification: {spec_name} ==="
echo ""
"""

VERIFY_FOOTER = """
echo ""
echo "=== Results: $PASSED passed, $FAILED failed (of $TOTAL) ==="

if [ "$FAILED" -gt 0 ]; then
    exit 1
fi
exit 0
"""


class GenericExporter:
    """Export spec as universal Markdown + shell verification script.

    Suitable for any AI agent or manual review. No tool-specific format.
    """

    def export(self, spec_dir: str, output_dir: str) -> list[str]:
        """Export the spec to generic format.

        Args:
            spec_dir: Path to the spec directory.
            output_dir: Path to write exported files.

        Returns:
            List of generated file paths.
        """
        spec_path = Path(spec_dir)
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        generated: list[str] = []
        spec_name = spec_path.name

        # Generate consolidated SPEC.md
        spec_md_path = out_path / "SPEC.md"
        spec_md_content = self._build_summary(spec_path, spec_name)
        spec_md_path.write_text(spec_md_content, encoding="utf-8")
        generated.append(str(spec_md_path))

        # Generate verify.sh
        verify_path = out_path / "verify.sh"
        verify_content = self._build_verify_script(spec_path, spec_name)
        verify_path.write_text(verify_content, encoding="utf-8")
        # Make executable
        verify_path.chmod(verify_path.stat().st_mode | stat.S_IEXEC)
        generated.append(str(verify_path))

        # Copy spec files for reference
        spec_out = out_path / "spec"
        spec_out.mkdir(exist_ok=True)
        for f in spec_path.iterdir():
            if f.is_file():
                dest = spec_out / f.name
                shutil.copy2(f, dest)
                generated.append(str(dest))

        logger.info(
            "generic_export_complete",
            output_dir=str(out_path),
            files=len(generated),
        )

        return generated

    def _build_summary(self, spec_path: Path, spec_name: str) -> str:
        """Build consolidated SPEC.md from all spec files.

        Args:
            spec_path: Path to the spec directory.
            spec_name: Name of the spec.

        Returns:
            Consolidated Markdown string.
        """
        sections: list[str] = [
            f"# Spec: {spec_name}",
            "",
            "> Generated by intake",
            "",
        ]

        # Include each spec file in order
        file_order = [
            ("context.md", "Project Context"),
            ("requirements.md", "Requirements"),
            ("design.md", "Design"),
            ("tasks.md", "Tasks"),
            ("sources.md", "Sources"),
        ]

        for filename, title in file_order:
            file_path = spec_path / filename
            if file_path.exists():
                content = file_path.read_text(errors="ignore").strip()
                sections.append("---\n")
                sections.append(f"## {title}\n")
                sections.append(content)
                sections.append("")

        return "\n".join(sections)

    def _build_verify_script(self, spec_path: Path, spec_name: str) -> str:
        """Build verify.sh from acceptance.yaml command checks.

        Args:
            spec_path: Path to the spec directory.
            spec_name: Name of the spec.

        Returns:
            Shell script content.
        """
        script = VERIFY_HEADER.format(spec_name=spec_name)

        acceptance_path = spec_path / "acceptance.yaml"
        if acceptance_path.exists():
            try:
                with open(acceptance_path) as f:
                    data = yaml.safe_load(f)
                checks = data.get("checks", []) if isinstance(data, dict) else []
            except yaml.YAMLError:
                checks = []

            for check in checks:
                if not isinstance(check, dict):
                    continue
                if check.get("type") == "command" and check.get("command"):
                    name = str(check.get("name", check.get("id", "unnamed")))
                    command = str(check["command"])
                    # Escape single quotes in command for shell safety
                    safe_command = command.replace("'", "'\\''")
                    script += f"check '{name}' '{safe_command}'\n"

        script += VERIFY_FOOTER
        return script
